// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crawl_jobs.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCrawlJob = `-- name: CreateCrawlJob :one
INSERT INTO crawl_jobs (id, status, start_url, error_message)
VALUES (
    gen_random_uuid(),
    $1, $2, $3
)
RETURNING id, created_at, updated_at, status, start_url, error_message
`

type CreateCrawlJobParams struct {
	Status       string
	StartUrl     string
	ErrorMessage sql.NullString
}

func (q *Queries) CreateCrawlJob(ctx context.Context, arg CreateCrawlJobParams) (CrawlJob, error) {
	row := q.db.QueryRowContext(ctx, createCrawlJob, arg.Status, arg.StartUrl, arg.ErrorMessage)
	var i CrawlJob
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StartUrl,
		&i.ErrorMessage,
	)
	return i, err
}

const getCrawlJobByID = `-- name: GetCrawlJobByID :one
SELECT id, created_at, updated_at, status, start_url, error_message FROM crawl_jobs WHERE id = $1
`

func (q *Queries) GetCrawlJobByID(ctx context.Context, id uuid.UUID) (CrawlJob, error) {
	row := q.db.QueryRowContext(ctx, getCrawlJobByID, id)
	var i CrawlJob
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StartUrl,
		&i.ErrorMessage,
	)
	return i, err
}

const updateCrawlJobStatus = `-- name: UpdateCrawlJobStatus :exec
UPDATE crawl_jobs
SET status = $2, updated_at = NOW(), error_message = $3
WHERE id = $1
`

type UpdateCrawlJobStatusParams struct {
	ID           uuid.UUID
	Status       string
	ErrorMessage sql.NullString
}

func (q *Queries) UpdateCrawlJobStatus(ctx context.Context, arg UpdateCrawlJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCrawlJobStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
