// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Restaurant struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	PlaceID    string
	Name       string
	SourceUrl  string
	Rating     float64
	PriceLevel int32
	Address    string
	Website    sql.NullString
	Telephone  sql.NullString
	Location   interface{}
	Types      []string
	Restroom   bool
}
