// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restaurants.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (id, created_at, updated_at, place_id, name, source_url, rating, price_level, address, website, telephone, location, types, restroom, image_url)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, created_at, updated_at, place_id, name, source_url, rating, price_level, address, website, telephone, location, types, restroom, image_url
`

type CreateRestaurantParams struct {
	PlaceID    string
	Name       string
	SourceUrl  string
	Rating     float64
	PriceLevel int32
	Address    string
	Website    sql.NullString
	Telephone  sql.NullString
	Location   interface{}
	Types      []string
	Restroom   bool
	ImageUrl   sql.NullString
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, createRestaurant,
		arg.PlaceID,
		arg.Name,
		arg.SourceUrl,
		arg.Rating,
		arg.PriceLevel,
		arg.Address,
		arg.Website,
		arg.Telephone,
		arg.Location,
		pq.Array(arg.Types),
		arg.Restroom,
		arg.ImageUrl,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlaceID,
		&i.Name,
		&i.SourceUrl,
		&i.Rating,
		&i.PriceLevel,
		&i.Address,
		&i.Website,
		&i.Telephone,
		&i.Location,
		pq.Array(&i.Types),
		&i.Restroom,
		&i.ImageUrl,
	)
	return i, err
}

const getRestaurantByID = `-- name: GetRestaurantByID :one
SELECT 
    id,
    place_id,
    name,
    source_url,
    rating,
    price_level,
    address,
    website,
    telephone,
    types,
    restroom,
    image_url,
    ST_AsGeoJSON(location)::jsonb AS location_json 
FROM restaurants
WHERE place_id = $1
`

type GetRestaurantByIDRow struct {
	ID           uuid.UUID
	PlaceID      string
	Name         string
	SourceUrl    string
	Rating       float64
	PriceLevel   int32
	Address      string
	Website      sql.NullString
	Telephone    sql.NullString
	Types        []string
	Restroom     bool
	ImageUrl     sql.NullString
	LocationJson json.RawMessage
}

func (q *Queries) GetRestaurantByID(ctx context.Context, placeID string) (GetRestaurantByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRestaurantByID, placeID)
	var i GetRestaurantByIDRow
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.SourceUrl,
		&i.Rating,
		&i.PriceLevel,
		&i.Address,
		&i.Website,
		&i.Telephone,
		pq.Array(&i.Types),
		&i.Restroom,
		&i.ImageUrl,
		&i.LocationJson,
	)
	return i, err
}

const getRestaurantBySourceURL = `-- name: GetRestaurantBySourceURL :one
SELECT id, created_at, updated_at, place_id, name, source_url, rating, price_level, address, website, telephone, location, types, restroom, image_url FROM restaurants WHERE source_url = $1
`

func (q *Queries) GetRestaurantBySourceURL(ctx context.Context, sourceUrl string) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, getRestaurantBySourceURL, sourceUrl)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlaceID,
		&i.Name,
		&i.SourceUrl,
		&i.Rating,
		&i.PriceLevel,
		&i.Address,
		&i.Website,
		&i.Telephone,
		&i.Location,
		pq.Array(&i.Types),
		&i.Restroom,
		&i.ImageUrl,
	)
	return i, err
}

const getRestaurants = `-- name: GetRestaurants :many
SELECT 
    id,
    place_id,
    name,
    source_url,
    rating,
    price_level,
    address,
    website,
    telephone,
    types,
    restroom,
    image_url,
    ST_AsGeoJSON(location)::jsonb AS location_json 
FROM restaurants
WHERE
    (name ILIKE '%' || $1::text || '%' OR $1 IS NULL) AND
    (rating >= $2 OR $2 IS NULL) AND
    (price_level = ANY($3::int[]) OR $3 IS NULL) AND
    (types && $4::text[] OR $4 IS NULL) AND
    (restroom = $5 OR $5 IS NULL)
ORDER BY rating DESC
LIMIT 9 OFFSET $6
`

type GetRestaurantsParams struct {
	Name        sql.NullString
	Rating      sql.NullFloat64
	PriceLevels []int32
	Types       []string
	Restroom    sql.NullBool
	Offset      sql.NullInt32
}

type GetRestaurantsRow struct {
	ID           uuid.UUID
	PlaceID      string
	Name         string
	SourceUrl    string
	Rating       float64
	PriceLevel   int32
	Address      string
	Website      sql.NullString
	Telephone    sql.NullString
	Types        []string
	Restroom     bool
	ImageUrl     sql.NullString
	LocationJson json.RawMessage
}

func (q *Queries) GetRestaurants(ctx context.Context, arg GetRestaurantsParams) ([]GetRestaurantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRestaurants,
		arg.Name,
		arg.Rating,
		pq.Array(arg.PriceLevels),
		pq.Array(arg.Types),
		arg.Restroom,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRestaurantsRow
	for rows.Next() {
		var i GetRestaurantsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.Name,
			&i.SourceUrl,
			&i.Rating,
			&i.PriceLevel,
			&i.Address,
			&i.Website,
			&i.Telephone,
			pq.Array(&i.Types),
			&i.Restroom,
			&i.ImageUrl,
			&i.LocationJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurantsCount = `-- name: GetRestaurantsCount :one
SELECT COUNT(*) FROM restaurants
WHERE
    (name ILIKE '%' || $1::text || '%' OR $1 IS NULL) AND
    (rating >= $2 OR $2 IS NULL) AND
    (price_level = ANY($3::int[]) OR $3 IS NULL) AND
    (types && $4::text[] OR $4 IS NULL) AND
    (restroom = $5 OR $5 IS NULL)
`

type GetRestaurantsCountParams struct {
	Name        sql.NullString
	Rating      sql.NullFloat64
	PriceLevels []int32
	Types       []string
	Restroom    sql.NullBool
}

func (q *Queries) GetRestaurantsCount(ctx context.Context, arg GetRestaurantsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRestaurantsCount,
		arg.Name,
		arg.Rating,
		pq.Array(arg.PriceLevels),
		pq.Array(arg.Types),
		arg.Restroom,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRestaurantsTypes = `-- name: GetRestaurantsTypes :many
SELECT DISTINCT unnest(types) AS type FROM restaurants
`

func (q *Queries) GetRestaurantsTypes(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.QueryContext(ctx, getRestaurantsTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var type_ interface{}
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
